[pr_reviewer]
require_score_review = false
require_tests_review = true
require_security_review = true
require_focused_review = true
num_code_suggestions = 4

[pr_description]
publish_labels = false
use_bullet_points = true

[config]
language = "zh"
